### ISSUE TITLE
Trouble compiling

### ISSUE THREAD

**Issue by jmcclena** [hoppe93/SOFT#1]
Hello, I am a researcher at General Atomics. I'm having some trouble compiling SOFT on my macbook SOFT due to the the gsl requirement. I have gsl version 2.1 installed by conda:

`gsl-config --prefix`
`/Users/mcclenaghanj/anaconda2`

`gsl-config --version`
`2.1`

However, when I try to run cmake:

`cmake ../ -DUSE_HDF5=OFF -DUSE_MATLAB=OFF`
`CMake Error at src/CMakeLists.txt:148 (message):
  SOFT needs GSL >= 2.0GSL_VERSION`

**Comment by hoppe93** [comment]
Hi! Sorry to hear you're having troubles compiling SOFT.

Based on the error message you get, it seems that CMake finds a GSL installation, but that it either it finds the wrong installation or that the version is reported incorrectly somehow (CMake has a few different ways of determining the GSL version).

Could you add the following on the line *directly after* `if (GSL_FOUND)` on line 135 in `src/CMakeLists.txt`:
```
message(STATUS ${GSL_VERSION})
message(STATUS ${GSL_INCLUDE_DIRS})
```
After rerunning `cmake` with the command you posted above you should get two new lines of output telling us the GSL version and the path to the library CMake finds.

// Mathias

**Comment by jmcclena** [comment]
Thanks! It was pointing to the wrong version of gsl, which was fixed when I cleared the CMakeCache. I ended up having more trouble with openmp on my mac. However, I ended up getting the code to compile on our local cluster(which is preferable).
