### ISSUE TITLE
The example pi files in the beginners guide are not working 

### ISSUE THREAD

**Issue by jmcclena** [hoppe93/SOFT#2]
I'm trying to figure out how to run SOFT with distribution function. However, links for the example pi files in the beginners guide are not working. 

<img width="877" alt="screen shot 2018-11-14 at 10 37 06 am" src="https://user-images.githubusercontent.com/13368621/48504440-99eb2e80-e7f9-11e8-9776-9b4f5dc5a47a.png">

**Comment by hoppe93** [comment]
Hi! I've been intending to add some example files for quite a while but it's just never happened. Since you gave me a reason to, I added the four example pi files under ``examples/`` in the repository. I've also updated the links in the documentation.
